# Name of your application. Used to uniquely configure containers.
service: blog

# Name of the container image.
image: thiagoramos23/blog

# Deploy to these servers.
servers:
  web:
    - 178.104.212.36
  #
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs
  #

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: thiagoramos.me
  # Proxy connects to your container on port 80 by default.
  app_port: 4000

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: thiagoramos23
  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  remote: ssh://root@178.104.212.36
  provenance: false
  sbom: false
  # Pass in additional build args needed for your Dockerfile.
  # args:
  #   RUBY_VERSION: <%= ENV["RBENV_VERSION"] || ENV["rvm_ruby_string"] || "#{RUBY_ENGINE}-#{RUBY_ENGINE_VERSION}" %>

# Inject ENV variables into containers (secrets come from .kamal/secrets).
#
env:
  clear:
    PORT: 4000
    MIX_ENV: prod
    PHX_HOST: thiagoramos.me
    PHX_SERVER: "true"
  secret:
    - DATABASE_URL
    - SECRET_KEY_BASE
# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal app logs -r job" will tail logs from the first server in the job section.
#
aliases:
  console: app exec --interactive "/app/bin/blog start_iex"
  shell: app exec --interactive "/bin/bash"
  logs: app logs -f

accessories:
  db:
    image: postgres:17
    host: 178.104.212.36
    port: 5432
    env:
      clear:
        POSTGRES_USER: "postgres"
        POSTGRES_DB: "blog_prod"
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
