import Config

# Configure your database
config :blog, Blog.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "blog_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

r2_account_id = System.get_env("R2_ACCOUNT_ID")
r2_access_key_id = System.get_env("R2_ACCESS_KEY_ID")
r2_secret_access_key = System.get_env("R2_SECRET_ACCESS_KEY")
r2_bucket = System.get_env("R2_BUCKET")
r2_public_url = System.get_env("R2_PUBLIC_URL")
r2_upload_prefix = System.get_env("R2_UPLOAD_PREFIX") || "posts"

if r2_account_id && r2_access_key_id && r2_secret_access_key do
  config :ex_aws,
    access_key_id: r2_access_key_id,
    secret_access_key: r2_secret_access_key

  config :ex_aws, :s3,
    scheme: "https://",
    host: "#{r2_account_id}.r2.cloudflarestorage.com",
    region: "auto"
end

if r2_bucket && r2_public_url do
  config :blog, Blog.Storage.R2,
    bucket: r2_bucket,
    public_url: r2_public_url,
    upload_prefix: r2_upload_prefix
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :blog, BlogWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "0o5ge+yOhL754qP047SgQDnucGfxNpT98CbDt1sgU5xNjvLGoup+OqL0yyTDpgP1",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :blog, BlogWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/blog_web/(live|views)/.*(ex)$",
      ~r"lib/blog_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Tidewave uses LiveView debug metadata to map UI elements back to source.
config :phoenix_live_view,
  debug_heex_annotations: true,
  debug_attributes: true

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
